Repository scp756-221/term-project-sfu_data_best_data, pull requests merged in 2022-03, with the labels that each got.

#23 Add playlist in Grafana and Gatling
  cluster/grafana-flask-configmap.yaml
  gatling-1-music.sh
  gatling/simulations/proj756/ReadTables.scala
  playlist/app.py
  s1/app.py
  s2/v1/app.py
  tools/gatling.sh
Labels: bug, task

#28 delete unnecessary files
  s2/v1.1/Dockerfile
  s2/v1.1/README.md
  s2/v1.1/a7_app.py
  s2/v1.1/a7_other_dev_app.py
  s2/v1.1/app.py
  s2/v1.1/requirements.txt
  s2/v1/app.py
  s2/v1/unique_code-tpl.py
Labels: subtask

#33 Load test
  cluster/cluster-autoscaler-autodiscover.yaml
  cluster/cluster-autoscaler-policy.json
  cluster/db-tpl.yaml
  cluster/namespace.yaml
  cluster/playlist-tpl.yaml
  cluster/s1-tpl.yaml
  cluster/s1-vs.yaml
  cluster/s2-dpl-v1-tpl.yaml
  cluster/scaling-policy.json
  cluster/tpl-vars-blank.txt
  ec2-gatling-pre.sh
  eks-tpl.mak
  gatling-1000-music.sh
  gatling-1000-playlist.sh
  gatling-1000-user.sh
  gatling-1000.sh
  helm-kube-stack-values.yaml
  k8s-tpl.mak
  profiles/aws-a
  profiles/ec2.mak
  tools/call-sed.sh
  tools/process-templates.sh
Labels: task

#34 Failure remediation and this part of report completed
  cluster/.gitignore
  cluster/db-vs-abort.yaml
  cluster/db-vs-delay.yaml
  cluster/playlist-svc.yaml
  cluster/playlist-vs-abort.yaml
  cluster/playlist-vs-canary-reroute.yaml
  cluster/playlist-vs-canary.yaml
  cluster/playlist-vs-circuit.yaml
  cluster/playlist-vs-delay.yaml
  cluster/playlist1-tpl.yaml
  cluster/playlist2-tpl.yaml
  k8s-tpl.mak
  playlist/v2/.gitignore
  playlist/v2/Dockerfile
  playlist/v2/app.py
  playlist/v2/requirements.txt
Labels: task
